version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 'senha123@Abc'
      MARIADB_DATABASE: 'projeto_pessoal'
      MARIADB_USER: 'usuario_app'
      MARIADB_PASSWORD: 'senha_segura'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    volumes:
      - ./config:/usr/local/etc/phpmyadmin

volumes:
  db_data: