version: '3.8'

services:
  mariadb:
    build: ./mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=meu_banco
      MYSQL_USER=usuario
      MYSQL_PASSWORD=senha
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST=mariadb
      PMA_USER=usuario
      PMA_PASSWORD=senha

volumes:
  mariadb_data: